# Generated by Django 4.0 on 2021-12-13 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cong_dan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('home_town', models.TextField()),
                ('permanent_address', models.TextField()),
                ('temporary_address', models.TextField()),
                ('religion', models.CharField(max_length=255)),
                ('educational_level', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
            ],
        ),
    ]
